baseURL = 'https://miguelcdpmarques3.netlify.com/'
languageCode = 'en-us'
title = 'Miguel Marques'
theme = 'toha'

[languages.en]
languageName = "English"
weight = 1

[markup.tableOfContents]
startLevel = 2
endLevel = 6
ordered = false

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
gitRepo = "https://github.com/hugo-toha/hugo-toha.github.io"
gitBranch = "main"
enableBlogPost = true
enableTOC = true

  [params.newsletter]
  enable = true
  provider = "mailchimp"
  mailchimpURL = "https://github.us1.list-manage.com/subscribe/post?u=19de52a4603135aae97163fd8&amp;id=094a24c76e"
